version: '3.8'

services:
  postgres:
    image: 'postgres:17'
    container_name: postgres-container
    environment:
      POSTGRES_USER: dofi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: folioflex
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
